### ISSUE TITLE
Platform

### ISSUE THREAD

**Issue by claudiiolima** [deltalejo/cppcheck-ceedling-plugin#2]
Hi @deltalejo, sorry for bugging you in the wrong repository, but since the `platform` plugin has been archived, this is where I can post any issues for you.

I use the `platform` plugin a lot in ceedling in v0.31.1, I'm trying to do the same but in v0.32.0, I know the tags are still pre-candidates, but I've already tried to adapt, but it's messing up with the `gcov` plugin . Everything works fine with the `ceedling platform:something release` and `ceedling platform:something test:all` tasks.
But with `ceedling platform:something gcov:all` an error occurs.

I think it's a `platform` plugin because it didn't happen when I just used `project.yml`. May you help me?

[platform fork](https://github.com/claudiiolima/ceedling-platforms-plugin/tree/main)
[gcov error](https://github.com/ThrowTheSwitch/Ceedling/issues/852)

> NOTE: I don't have any Ruby or Rake skills, nor do I know how I could debug the error.

**Comment by deltalejo** [comment]
Hi @claudiiolima!
I stopped working on that plugin precisely because I also found it messes around with a few things and to be honest the plugin is a bit hacky. Anyway, I manage to achieve the same result in a cleaner way by using a rakefile. I've been working on an example project [here](https://github.com/deltalejo/ceedling-microchip-example), it is for Microchip devices, but maybe you can take some ideas from there, specially the [rakefile](https://github.com/deltalejo/ceedling-microchip-example/blob/main/rakefile.rb). However, according to the preliminary release notes for Ceedling v0.32, Rake support is going to be dropped out, so in the future we need to figure out a way to achieve the same result with whatever mechanism the upcoming Ceedling releases provide.
Let me know if the above works for you and feel free to email me if you need so.

**Comment by claudiiolima** [comment]
It so much cleaner, just use the rakefile was enough for me, thank you very much.

Maybe you can help one more time before closing the problem, when I use the rakefile as you proposed, some warnings appeared in the prompt during the beginning of the process. Like that:

```bash
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ceedling-0.32.0/lib/ceedling/constants.rb:113: warning: already initialized constant VENDORS_FILES
~/vendor/ceedling/lib/ceedling/constants.rb:113: warning: previous definition of VENDORS_FILES was here
```

Is there something I need to do to fix or hide this warnings?

> NOTE: I am not using platforms nor mdb, just the rakefile.

**Comment by deltalejo** [comment]
It does not happen to me with the example project, maybe there is something odd in your rakefile or project setup.

**Comment by claudiiolima** [comment]
I was using ceedling as local package and including gem by using `require("ceedling")`.

Using `load "../vendor/Ceedling/lib/ceedling.rb"` instead, the warnigns were gone.
