### ISSUE TITLE
Project parsing the enviroment variables

### ISSUE THREAD

**Issue by claudiiolima** [deltalejo/cppcheck-ceedling-plugin#6]
@deltalejo may you can help me.

Testing the modifications I made at last merge, the new option `project`, does not parse the enviroment variables, for example.

```yaml
:project: ../output_files/bin/#{ENV['CUSTOMER']}/compile_commands.json
```

```shell
$...ceedling/tool_executor.rb:78:in `exec': 'Default Cppcheck' (cppcheck.exe) terminated with exit code [1] and output >> "cppcheck: error: failed to open project '../output_files/bin/#{ENV['CUSTOMER']}/compile_commands.json'. The file does not exist."
```

What I need to change to make this work?

**Comment by claudiiolima** [comment]
I tried other fields (`template`, `standard`), doesn't work too. But some fields as `html_artifact_dirname` seems to work.

**Comment by deltalejo** [comment]
I'll be surprised if any of the config options evaluate environment variables as I didn't implement that. It can be easily done, you just need to check if the config value matches the Ceedling Ruby replacement string pattern and perform the evaluation, e.g.:

```ruby
if @config[:project] =~ RUBY_STRING_REPLACEMENT_PATTERN
  @config[:project].replace(
    @system_wrapper.module_eval(@config[:project])
  )
end
```

As a reference, I did so in another plugin, look [here](https://github.com/deltalejo/ceedling-mdb-plugin/blob/64ee4bc895a00ae7ffcd68e04f9965ba8e386d86/lib/mdb.rb#L38), it supports environment variables evaluation on `:device` and `:hwtool` options.

Regarding `html_artifact_dirname` option, it is not handle at all, that's why you are not seeing an error for that, it should be removed from the docs.

**Comment by claudiiolima** [comment]
Ok, I will do the modifications and start a PR
